CREATE TABLE IF NOT EXISTS company (
id SERIAL NOT NULL PRIMARY KEY,
name CHARACTER VARYING
);

CREATE TABLE IF NOT EXISTS person (
id SERIAL NOT NULL PRIMARY KEY,
name CHARACTER VARYING,
company_id integer REFERENCES company(id)
);